org: derickavila
app: lambda-api-template
service: lambda-api-template

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    NODE_ENV: ${env:NODE_ENV}


plugins:
  - serverless-offline

custom:
  serverless-offline:
    stage: "api"

functions:
  app:
    handler: handler.app
    events:
      - http:
          path: /
          method: any
      - http:
          path: /{proxy+}
          method: any
